// JEU 
const GAME_HEIGHT = 288
const GAME_WIDTH = 512
const FONDU_CAM = 3000

// PNJ
const MARCHAND_TRIGGER = 100
const PNJ_TRIGGER = 100

// PLAYER
const PLAYER_SPEED = 180 
const PLAYER_INVINCIBLE = 900

//ZOMBIE
const ZOMBIE_SPEED = 50
const ZOMBIE_RANGE = 225

// BOSS
const BOSS_MAX_HEALT = 80
const BOSS_MOVE_SPEED_PHASE_1 = 50
const BOSS_MOVE_SPEED_PHASE_2 = 100
const BOSS_DETECTION_DISTANCE = 300


